# Generated by Django 2.2.4 on 2019-08-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
            preserve_default=False,
        ),
    ]
