# Generated by Django 2.2.5 on 2019-09-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UfCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.TextField(max_length=2)),
                ('total_campus', models.IntegerField()),
            ],
        ),
    ]
